

#' Forecast Human Mortality
#' 
#' @param object An object of the class \code{MotalityModels} generated by the
#' \code{\link{doMortalityModels}} function.
#' @param ... Further argumets to be passed to other methods.
#' @inheritParams CoDa::predict.coda
#' @export
doForecasts <- function(object, h, ci = 95, 
                        jumpchoice = c("actual", "fit"), ...) {
  jumpchoice <- match.arg(jumpchoice)
  
  x <- object$x
  y <- max(object$y) + 1:h
  M1 <- object$PLC
  M2 <- object$codaLC
  M3 <- object$LC
  
  P1 <- predict(M1, h = h, jumpchoice = jumpchoice, ci = ci)
  P2 <- predict(M2, h = h, jumpchoice = jumpchoice, ci = ci)
  P3 <- forecast(M3, h = h, jumpchoice = jumpchoice, level = ci)
  
  out <- list(call = match.call(), PLC = P1, codaLC = P2, LC = P3, 
              x = x, y = y)
  out <- structure(class = "doForecasts", out)
  return(out)
}

#' Get Predicted Values
#' 
#' @param object An object of class \code{predict.MortalityModels}
#' @inheritParams getFitted
#' @export
#' 
getForecasts <- function(object, 
                      type = c("qx", "mx", "dx", "lx", "Lx", "Tx", "ex"),
                      ...) {
  type <- match.arg(type)
  x    <- object$x
  
  dx1 <- object$PLC$predicted.values
  dx2 <- object$codaLC$predicted.values
  mx3 <- object$LC$rates
  dx3 <- fx2gx(x, mx3, In = "mx", Out = "dx", lx0 = 1)
  
  dx  <- list(dx1, dx2, dx3)
  fn  <- function(Z) fx2gx(x, Z, In = "dx", Out = type, lx0 = 1)
  out <- lapply(dx, fn)
  names(out) <- c("PLC", "codaLC", "LC")
  return(out)
}
